name: s2geometry
description: Dart port of the S2 Geometry library
version: 0.1.1
homepage: https://github.com/nbspou/dart-s2geometry

environment:
  sdk: '>=3.3.3 <4.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
